version: "3.8"

services:
  postgres:
    image: postgres:12.4
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backup:/backup
    networks:
      - delivery
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_USER=delivery
      - POSTGRES_PASSWORD=delivery

networks:
  delivery:
    driver: bridge
